# fly.toml app configuration file generated for pocketgardener on 2024-07-07T23:53:59+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pocketgardener'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
